### ISSUE TITLE
Split unit test and actual function/library

### ISSUE THREAD

**Issue by mebibou** [GPawi/Interview_Task_Oxford#1]
If we were to use this as a library, we wouldn't want to run the tests every time we use the function. Therefore would it be possible to have:
- a folder like "tests" where the test files are
- the function in a file that only contains the function

Then the Github Actions could simply run the tests and make sure they pass

**Comment by GPawi** [comment]
Hi Guillaume,

thanks for the tip. I changed the repository and it now also passes the GitHub Action test.
